const INTERNAl_SERVER_ERROR = 500;
const NOT_FOUND = 404;
const RESPONSE_ERROR = 400;
const SUCCESS = 200;
const FAILURE = 300;

export { INTERNAl_SERVER_ERROR, NOT_FOUND, RESPONSE_ERROR, SUCCESS, FAILURE };
