import {
  home,
  homeGreen,
  invoices,
  invoicesGreen,
  profile,
  profileGreen,
  services,
  servicesGreen,
  Signout,
  SignoutGreen,
  store,
  storeGreen,
  support,
  supportGreen,
} from '../assets';

export const sidebarContent = [
  {
    id: 1,
    titleEn: 'Home',
    titleAr: 'الصفحة الرئيسية',
    icon: home,
    greenIcon: homeGreen,
    route: 'home',
  },
  {
    id: 2,
    titleEn: 'My Profile',
    titleAr: 'ملفي',
    icon: profile,
    greenIcon: profileGreen,
    route: 'myProfile',
  },
  {
    id: 3,
    titleEn: 'Plans & Services',
    titleAr: 'الخطط والخدمات',
    icon: services,
    greenIcon: servicesGreen,
    route: 'plansAndServices',
  },
  {
    id: 4,
    titleEn: 'Invoices',
    titleAr: 'الفواتير',
    icon: invoices,
    greenIcon: invoicesGreen,
    route: 'invoices',
  },
  {
    id: 5,
    titleEn: 'Store',
    titleAr: 'متجر',
    icon: store,
    greenIcon: storeGreen,
    route: 'store',
  },
  {
    id: 6,
    titleEn: 'Support',
    titleAr: 'الدعم',
    icon: support,
    greenIcon: supportGreen,
    route: 'support',
  },
  // {
  //   id: 7,
  //   titleEn: 'Sign Out',
  //   titleAr: 'خروج',
  //   icon: Signout,
  //   greenIcon: SignoutGreen,
  //   route: 'signOut',
  // },
];
